version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork
    environment:
      - BACKEND_URL=http://backend:5000

networks:
  mynetwork:
    driver: bridge